# Generated by Django 6.0.2 on 2026-02-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eidevent',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
